title: jbirky
description: my webpage
sitename: Jessica Birky
baseurl: 'https://jbirky.github.io'
sass:
  sass_dir: /assets/_sass
  style: :compress
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME